"""creating users table

Revision ID: 350deb44adac
Revises: e7bbbb2d6585
Create Date: 2023-01-04 01:04:19.420579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '350deb44adac'
down_revision = 'e7bbbb2d6585'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
